/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//import static com.mysql.cj.MysqlType.NULL;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author rushi
 */
public class BookingScreen extends javax.swing.JFrame {

    /**
     * Creates new form BookingScreen
     */
    
    Image img = Toolkit.getDefaultToolkit().getImage("F:\\map.jpg");
    public BookingScreen() {
        this.setContentPane(new JPanel()
                {
                    @Override
                    public void paintComponent(Graphics g)
                {
                    super.paintComponent(g);
                    g.drawImage(img, 0, 0, 758, 510, this);
                }
                });
        setResizable(false);
        try{
        loc_a_drop.setEnabled(false);
        }
        catch (Exception e){}
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dest_butt_group = new javax.swing.ButtonGroup();
        jRadioButton12 = new javax.swing.JRadioButton();
        loc_butt_group = new javax.swing.ButtonGroup();
        car_type_group = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        book_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loc_a_pick = new javax.swing.JRadioButton();
        loc_b_pick = new javax.swing.JRadioButton();
        loc_c_pick = new javax.swing.JRadioButton();
        loc_d_pick = new javax.swing.JRadioButton();
        loc_e_pick = new javax.swing.JRadioButton();
        loc_f_pick = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        loc_a_drop = new javax.swing.JRadioButton();
        loc_b_drop = new javax.swing.JRadioButton();
        loc_c_drop = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        car_mini = new javax.swing.JRadioButton();
        car_suv = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        loc_d_drop = new javax.swing.JRadioButton();
        loc_e_drop = new javax.swing.JRadioButton();
        loc_f_drop = new javax.swing.JRadioButton();
        loc_g_pick = new javax.swing.JRadioButton();
        loc_h_pick = new javax.swing.JRadioButton();
        loc_g_drop = new javax.swing.JRadioButton();
        loc_h_drop = new javax.swing.JRadioButton();

        jRadioButton12.setText("Location F");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Book Your Ride");

        book_button.setText("Book Now");
        book_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_buttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Pick-Up Location");

        loc_butt_group.add(loc_a_pick);
        loc_a_pick.setText("Location A");

        loc_butt_group.add(loc_b_pick);
        loc_b_pick.setText("Location B");
        loc_b_pick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loc_b_pickActionPerformed(evt);
            }
        });

        loc_butt_group.add(loc_c_pick);
        loc_c_pick.setText("Location C");

        loc_butt_group.add(loc_d_pick);
        loc_d_pick.setText("Location D");

        loc_butt_group.add(loc_e_pick);
        loc_e_pick.setText("Location E");
        loc_e_pick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loc_e_pickActionPerformed(evt);
            }
        });

        loc_butt_group.add(loc_f_pick);
        loc_f_pick.setText("Location F");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Drop Location");

        dest_butt_group.add(loc_a_drop);
        loc_a_drop.setText("Location A");

        dest_butt_group.add(loc_b_drop);
        loc_b_drop.setText("Location B");

        dest_butt_group.add(loc_c_drop);
        loc_c_drop.setText("Location C");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Ride Type");

        car_type_group.add(car_mini);
        car_mini.setText("Mini");

        car_type_group.add(car_suv);
        car_suv.setText("SUV");

        dest_butt_group.add(loc_d_drop);
        loc_d_drop.setText("Location D");

        dest_butt_group.add(loc_e_drop);
        loc_e_drop.setText("Location E");

        dest_butt_group.add(loc_f_drop);
        loc_f_drop.setText("Location F");

        loc_butt_group.add(loc_g_pick);
        loc_g_pick.setText("Location G");
        loc_g_pick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loc_g_pickActionPerformed(evt);
            }
        });

        loc_butt_group.add(loc_h_pick);
        loc_h_pick.setText("Location H");
        loc_h_pick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loc_h_pickActionPerformed(evt);
            }
        });

        dest_butt_group.add(loc_g_drop);
        loc_g_drop.setText("Location G");

        dest_butt_group.add(loc_h_drop);
        loc_h_drop.setText("Location H");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(511, 511, 511)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(loc_a_pick)
                                    .addComponent(loc_b_pick)
                                    .addComponent(loc_c_pick)
                                    .addComponent(loc_g_pick)
                                    .addComponent(loc_h_pick))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loc_c_drop)
                                    .addComponent(loc_b_drop)
                                    .addComponent(loc_a_drop)
                                    .addComponent(jLabel3)
                                    .addComponent(loc_d_drop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loc_e_drop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loc_f_drop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loc_g_drop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loc_h_drop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(book_button))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(car_mini, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(car_suv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(loc_d_pick)
                            .addComponent(loc_e_pick)
                            .addComponent(loc_f_pick)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loc_a_pick)
                    .addComponent(loc_a_drop)
                    .addComponent(car_mini))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loc_b_pick)
                    .addComponent(loc_b_drop)
                    .addComponent(car_suv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loc_c_pick)
                    .addComponent(loc_c_drop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loc_d_pick)
                    .addComponent(loc_d_drop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loc_e_pick)
                    .addComponent(loc_e_drop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loc_f_pick)
                    .addComponent(loc_f_drop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loc_g_drop)
                    .addComponent(loc_g_pick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loc_h_drop)
                    .addComponent(loc_h_pick))
                .addGap(42, 42, 42)
                .addComponent(book_button)
                .addGap(72, 72, 72)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void book_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_buttonActionPerformed

        if(!loc_a_pick.isSelected() && !loc_b_pick.isSelected() && !loc_c_pick.isSelected() && !loc_d_pick.isSelected() && !loc_e_pick.isSelected() && !loc_f_pick.isSelected() && !loc_g_pick.isSelected() && !loc_h_pick.isSelected())
        {
        //displaying error if no pick-up is selected
            JOptionPane.showMessageDialog (null,"Please select a pick-up location");
        }
        
        else if(!loc_a_drop.isSelected()&&!loc_b_drop.isSelected()&&!loc_c_drop.isSelected()&&!loc_d_drop.isSelected()&&!loc_e_drop.isSelected()&&!loc_f_drop.isSelected()&&!loc_g_drop.isSelected()&&!loc_h_drop.isSelected())
        {
        //displaying error if no drop is selected
            JOptionPane.showMessageDialog (null,"Please select a drop location");
        }
        
        else if(!car_mini.isSelected()&&!car_suv.isSelected())
        {
        //displaying error if no car is selected
            JOptionPane.showMessageDialog (null,"Please select a car type");
        }
        
        else if(true)
        {
            String pickup,drop;
        } 
        
    }//GEN-LAST:event_book_buttonActionPerformed

    private void loc_b_pickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loc_b_pickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loc_b_pickActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void loc_e_pickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loc_e_pickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loc_e_pickActionPerformed

    private void loc_g_pickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loc_g_pickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loc_g_pickActionPerformed

    private void loc_h_pickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loc_h_pickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loc_h_pickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book_button;
    private javax.swing.JRadioButton car_mini;
    private javax.swing.JRadioButton car_suv;
    private javax.swing.ButtonGroup car_type_group;
    private javax.swing.ButtonGroup dest_butt_group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton loc_a_drop;
    private javax.swing.JRadioButton loc_a_pick;
    private javax.swing.JRadioButton loc_b_drop;
    private javax.swing.JRadioButton loc_b_pick;
    private javax.swing.ButtonGroup loc_butt_group;
    private javax.swing.JRadioButton loc_c_drop;
    private javax.swing.JRadioButton loc_c_pick;
    private javax.swing.JRadioButton loc_d_drop;
    private javax.swing.JRadioButton loc_d_pick;
    private javax.swing.JRadioButton loc_e_drop;
    private javax.swing.JRadioButton loc_e_pick;
    private javax.swing.JRadioButton loc_f_drop;
    private javax.swing.JRadioButton loc_f_pick;
    private javax.swing.JRadioButton loc_g_drop;
    private javax.swing.JRadioButton loc_g_pick;
    private javax.swing.JRadioButton loc_h_drop;
    private javax.swing.JRadioButton loc_h_pick;
    // End of variables declaration//GEN-END:variables
}
