
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rushi
 */
public class DriverPage extends javax.swing.JFrame {
    String pickup_g, drop_g, driver_name_g;
    int fare_g;
    float driver_rating_g;
    /**
     * Creates new form DriverPage
     */
    public DriverPage(String pickup, String drop, int fare, String driver_name, float driver_rating) {

        setResizable(false);
        initComponents();
        final_fare_val.setFont(new java.awt.Font("Dialog", 1, 24));
        final_fare_val.setText("" + fare + "");
        fare_g = fare;
        
        pick_loc_val.setFont(new java.awt.Font("Dialog", 1, 24));
        pick_loc_val.setText(pickup);
        pickup_g = pickup;
        
        drop_loc_val.setFont(new java.awt.Font("Dialog", 1, 24));
        drop_loc_val.setText(drop);
        drop_g = drop;
        
        dri_name_val.setFont(new java.awt.Font("Dialog", 1, 24));
        dri_name_val.setText(driver_name);
        driver_name_g = driver_name;
        
        dri_rating_val.setFont(new java.awt.Font("Dialog", 1, 24));
        dri_rating_val.setText(String.valueOf(driver_rating));
        driver_rating_g = driver_rating;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dri_name = new javax.swing.JLabel();
        dri_rating = new javax.swing.JLabel();
        pick_loc = new javax.swing.JLabel();
        drop_loc = new javax.swing.JLabel();
        coupon_code = new javax.swing.JLabel();
        verify_code = new javax.swing.JButton();
        final_fare = new javax.swing.JLabel();
        confirm_booking = new javax.swing.JButton();
        final_fare_val = new javax.swing.JLabel();
        pick_loc_val = new javax.swing.JLabel();
        drop_loc_val = new javax.swing.JLabel();
        dri_name_val = new javax.swing.JLabel();
        dri_rating_val = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coupon_input = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Driver Details");

        dri_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dri_name.setText("Driver Name:");

        dri_rating.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dri_rating.setText("Driver Rating:");

        pick_loc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pick_loc.setText("Pick-Up Location:");

        drop_loc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        drop_loc.setText("Drop Location:");

        coupon_code.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        coupon_code.setText("Coupon Code:");

        verify_code.setText("Verify Code");
        verify_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify_codeActionPerformed(evt);
            }
        });

        final_fare.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        final_fare.setText("Final Fare:");

        confirm_booking.setText("Confirm Booking");
        confirm_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_bookingActionPerformed(evt);
            }
        });

        coupon_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coupon_inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drop_loc)
                            .addComponent(pick_loc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pick_loc_val, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(246, 246, 246))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(confirm_booking)
                                        .addComponent(verify_code))
                                    .addGap(73, 73, 73)))
                            .addComponent(drop_loc_val, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(coupon_code)
                                    .addComponent(final_fare, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coupon_input, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(final_fare_val, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dri_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dri_rating, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dri_rating_val, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dri_name_val, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(195, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(pick_loc_val, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pick_loc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(drop_loc_val, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drop_loc))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dri_name)
                    .addComponent(dri_name_val, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(dri_rating))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(dri_rating_val, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coupon_code)
                    .addComponent(verify_code)
                    .addComponent(jLabel13)
                    .addComponent(coupon_input, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(confirm_booking)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(final_fare)
                            .addComponent(final_fare_val, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirm_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_bookingActionPerformed
        // TODO add your handling code here:
        
        // Change the driver status here to 1 and increase the number of trips and then continue
        // Gaurang is adding the drivers ka refreshing algo here. So contact him for any problems;
        int tot_trips=0;
	try
	{
            Class.forName("com.mysql.jdbc.Driver");
            Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/drivers?characterEncoding=latin1","root","root");
            Statement myStmt = myConn.createStatement();
            ResultSet myRs = myStmt.executeQuery("select * from driver");
            while(myRs.next())
            {
		tot_trips+=myRs.getInt("num_trips");
            }
            tot_trips-=150;
            if(tot_trips%5==0)
            {
            	String upda="Update driver set cur_pos = initial_pos where cur_status = 0 ";
            	myStmt.executeUpdate(upda);
            }
	}
        catch(Exception e)
	{
        System.out.println(e);
	}
        dispose();
        TravelPage tp = new TravelPage(pickup_g,drop_g,driver_name_g,fare_g/10,fare_g);
        tp.setVisible(true);
    }//GEN-LAST:event_confirm_bookingActionPerformed

    private void coupon_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coupon_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coupon_inputActionPerformed

    private void verify_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify_codeActionPerformed
        // TODO add your handling code here:
        String a = coupon_input.getText();
        //JOptionPane.showMessageDialog (null,a);
        String flag = "";
        double fare_temp = fare_g;
        //JOptionPane.showMessageDialog (null,String.valueOf(fare));
//the value of fare is being picked from the constructor method
        
        try
        {
            int p=0;
            Class.forName("com.mysql.jdbc.Driver");
            Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/coupon?characterEncoding=latin1","root","root");
            Statement myStmt = myConn.createStatement();
            ResultSet myRs = myStmt.executeQuery("select * from coup_details" );
            while(myRs.next())
            {
                if(myRs.getString("code").equals(a))
                {
                    p++;
                    double discount = myRs.getInt("value")/100.0;
                    //JOptionPane.showMessageDialog (null,String.valueOf(discount));
                    fare_temp = fare_temp * (1 - discount);
                    //JOptionPane.showMessageDialog (null,String.valueOf(fare));
                    final_fare_val.setFont(new java.awt.Font("Dialog", 1, 24));
                    final_fare_val.setText("" + String.valueOf(fare_temp) + "");
                }
            }
            if(p==0)
            {
                JOptionPane.showMessageDialog(null,"The given coupon does not exist");
            }
        }
        
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_verify_codeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DriverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DriverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DriverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DriverPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DriverPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm_booking;
    private javax.swing.JLabel coupon_code;
    private javax.swing.JTextField coupon_input;
    private javax.swing.JLabel dri_name;
    private javax.swing.JLabel dri_name_val;
    private javax.swing.JLabel dri_rating;
    private javax.swing.JLabel dri_rating_val;
    private javax.swing.JLabel drop_loc;
    private javax.swing.JLabel drop_loc_val;
    private javax.swing.JLabel final_fare;
    private javax.swing.JLabel final_fare_val;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel pick_loc;
    private javax.swing.JLabel pick_loc_val;
    private javax.swing.JButton verify_code;
    // End of variables declaration//GEN-END:variables
}
